package tests

// Code generated by Mikaël's proxy generator. DO NOT EDIT.

import (
	context "context"
	xml "encoding/xml"
	constraint "go/build/constraint"
	alias "net/http/httptest"
)

type MyServiceProxy struct {
	delegate          *MyService
	invocationHandler func(method interface {
		Package() string
		Receiver() string
		Name() string
		Invoke(args []any) []any
	}, args []any) []any
}

type _MyServiceMethod struct {
	methodName string
	receiver   string
	method     func([]any) []any
}

func (m *_MyServiceMethod) Name() string { return m.methodName }

func (m *_MyServiceMethod) Receiver() string { return m.receiver }

func (m *_MyServiceMethod) Package() string { return "tests" }

func (m *_MyServiceMethod) Invoke(args []any) []any { return m.method(args) }

func (d *MyServiceProxy) NoArgsMethod() {
	method := _MyServiceMethod{
		methodName: "NoArgsMethod",
		receiver:   "*MyService",
		method: func(args []any) []any {
			d.delegate.NoArgsMethod()
			return []any{}
		},
	}

	var args []any
	d.invocationHandler(&method, args)
}

func (d *MyServiceProxy) ContextMethod(ctx context.Context) {
	method := _MyServiceMethod{
		methodName: "ContextMethod",
		receiver:   "*MyService",
		method: func(args []any) []any {
			d.delegate.ContextMethod(args[0].(context.Context))
			return []any{}
		},
	}

	var args []any = []any{ctx}
	d.invocationHandler(&method, args)
}

func (d *MyServiceProxy) OneArgErrorMethod() error {
	method := _MyServiceMethod{
		methodName: "OneArgErrorMethod",
		receiver:   "*MyService",
		method: func(args []any) []any {
			result0 := d.delegate.OneArgErrorMethod()
			return []any{result0}
		},
	}

	var args []any
	results := d.invocationHandler(&method, args)
	return results[0].(error)
}

func (d *MyServiceProxy) TwoArgsErrorMethod(ctx context.Context, aStruct Struct) (string, error) {
	method := _MyServiceMethod{
		methodName: "TwoArgsErrorMethod",
		receiver:   "*MyService",
		method: func(args []any) []any {
			result0, result1 := d.delegate.TwoArgsErrorMethod(args[0].(context.Context), args[1].(Struct))
			return []any{result0, result1}
		},
	}

	var args []any = []any{ctx, aStruct}
	results := d.invocationHandler(&method, args)
	return results[0].(string), results[1].(error)
}

func (d *MyServiceProxy) ArgsWithComplexImportPathsAndAlias(a xml.CharData, b constraint.Expr, server alias.ResponseRecorder) {
	method := _MyServiceMethod{
		methodName: "ArgsWithComplexImportPathsAndAlias",
		receiver:   "*MyService",
		method: func(args []any) []any {
			d.delegate.ArgsWithComplexImportPathsAndAlias(args[0].(xml.CharData), args[1].(constraint.Expr), args[2].(alias.ResponseRecorder))
			return []any{}
		},
	}

	var args []any = []any{a, b, server}
	d.invocationHandler(&method, args)
}

func NewMyServiceProxy(delegate *MyService, invocationHandler func(method interface {
	Package() string
	Receiver() string
	Name() string
	Invoke(args []any) []any
}, args []any) (retVals []any)) *MyServiceProxy {
	if invocationHandler == nil {
		invocationHandler = func(method interface {
			Package() string
			Receiver() string
			Name() string
			Invoke(args []any) []any
		}, args []any) []any {
			return method.Invoke(args)
		}
	}

	return &MyServiceProxy{
		delegate:          delegate,
		invocationHandler: invocationHandler,
	}
}
